# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main
  
pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'quarkus-api'
  DOCKER_USERNAME: sarahribeiro123
  DOCKER_PASSWORD: $(DOCKER_ACCESS_TOKEN)

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: Install JDK 17

- script: echo "Setting JAVA_HOME to JDK 17 location."
  displayName: 'Set JAVA_HOME to JDK 17'

- script: |
    java -version
    echo "JVM: $(java -version)"
  displayName: 'Check Java Version'

- script: |
    chmod +x ./mvnw
    ./mvnw clean
  displayName: Clean project

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: Build of the application
    
- script: |
    docker --version
    sudo service docker start
    docker --version
  displayName: Show Docker version

- script: |
    chmod +x ./mvnw
    ./mvnw package -Dnative -Dquarkus.native.container-build=true
  displayName: Build a native Linux executable

- script: |
    docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
  displayName: Docker login

- script: |
    docker build -f src/main/docker/Dockerfile.native -t $(imageName) .
  displayName: Build the container image
  
- script: |
    docker tag $(imageName) $(DOCKER_USERNAME)/$(imageName):latest
    docker push $(DOCKER_USERNAME)/$(imageName):latest
  displayName: Push Docker image to Docker Hub